keys:
  - &moth_gpg C5C84658CCFD7E8E71DEE933AF3AE54FC3A35C9F
  - &pcLexell_age age1vzctvstte5cf8dru8hdukualgwfzz9zf4enxx8a5cznyxu450shshw8tzs
creation_rules:
    - path_regex: secrets/[^/]+\.yaml$
    - pgp: *moth_gpg
    - age: *pcLexell_age
